# Generated by Django 2.2.6 on 2019-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191101_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
